### ISSUE TITLE
Could not run chat gpt with error :: TypeError: The "listener" argument must be of type Function. Received type object

### ISSUE THREAD

**Issue by goforbg** [abacaj/unofficial-chatgpt-api#2]
Hi I tried running this library in a chrome extension with the below code as mentioned in the about, 

I get the error **Could not run chat gpt with error :: TypeError: The "listener" argument must be of type Function. Received type object**

```     //Ask the prompt
        const gpt = new ChatGPTClient({ sessionToken0: session_token});
        const convo = await gpt.startConversation();
        const response = await convo.chat(prompt)

        // response is a markdown-formatted string
        window.alert(response.message.content.parts)```

How do I fix it?

**Comment by abacaj** [comment]
Hi, unfortunately this library only works in a Node.js environment.
