### ISSUE TITLE
Uncaught (in promise) TypeError: The "listener" argument must be of type Function. Received type object

### ISSUE THREAD

**Issue by khoatran1602** [abacaj/unofficial-chatgpt-api#3]
``const generateCV = async () => {
    const gpt = new ChatGPTClient({
      clearanceToken:
        "dwSMzZOKKeuNhACRm1oLFmbhFb4cHRzsBcVEdKvSOzw-1670796550-0-160",
      sessionToken0: process.env.NEXT_PUBLIC_SESSION_TOKEN!,
    });
    const convo = await gpt.startConversation(); //This line causes the error
    const m2 = await convo.chat("what year is it?");
    console.log(m2.message.content.parts);
  };
Hi, i'm having the issue with the type error and i dont know what this is. Can you take a look?

**Comment by abacaj** [comment]
Hi @khoatran1602 are you using the library in a browser environment or Node.js?

**Comment by khoatran1602** [comment]
im using nextjs, just tried to grab the text and display on my localhost website

**Comment by abacaj** [comment]
> im using nextjs, just tried to grab the text and display on my localhost website

You'll need to use it in an api route and return the response to your client javascript, I also use this in a nextjs app but only reference the library in a api route

**Comment by khoatran1602** [comment]
hm... so i need to use the configuration in the api route right?

**Comment by khoatran1602** [comment]
thanks

**Comment by abacaj** [comment]
Here's a sample, create a file called `chat.js` under `pages/api`:

```js
import { NextApiRequest, NextApiResponse } from 'next';
import { ChatGPTClient } from 'unofficial-chatgpt-api';

const gpt = new ChatGPTClient({
  clearanceToken:
    process.env.CLEARANCE_TOKEN!,
  sessionToken0: process.env.NEXT_PUBLIC_SESSION_TOKEN!,
});

export default async function handler(
  req,
  res,
) {
  const convo = await gpt.startConversation();
  const m2 = await convo.chat('what year is it?');

  res.json({
    message: m2.message.content.parts,
  });
}
```

![image](https://user-images.githubusercontent.com/7272343/206935878-787a21eb-063b-4846-8f28-77052fe58bde.png)

**Comment by abacaj** [comment]
Marking as closed, please open another issue if you have another question - thanks!
