### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by khoatran1602** [abacaj/unofficial-chatgpt-api#4]
Hi, yesterday i could get the data from chatGPT but today i get the error: Server Error Forbidden. When i check the Source the api is HTML type below. Do you know why this happens?
`<!DOCTYPE html><html><head><style data-next-hide-fouc="true">body{display:none}</style><noscript data-next-hide-fouc="true"><style>body{display:block}</style></noscript><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills.js?ts=1670878227794"></script><script src="/_next/static/chunks/webpack.js?ts=1670878227794" defer=""></script><script src="/_next/static/chunks/main.js?ts=1670878227794" defer=""></script><script src="/_next/static/chunks/pages/_app.js?ts=1670878227794" defer=""></script><script src="/_next/static/chunks/pages/_error.js?ts=1670878227794" defer=""></script><script src="/_next/static/development/_buildManifest.js?ts=1670878227794" defer=""></script><script src="/_next/static/development/_ssgManifest.js?ts=1670878227794" defer=""></script><noscript id="__next_css__DO_NOT_USE__"></noscript></head><body><div id="__next"></div><script src="/_next/static/chunks/react-refresh.js?ts=1670878227794"></script><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":500}},"page":"/_error","query":{"__NEXT_PAGE":"/api"},"buildId":"development","isFallback":false,"err":{"name":"Error","source":"server","message":"Forbidden","stack":"Error: Forbidden\n    at ClientRequest.\u003canonymous\u003e (C:\\Users\\LENOVO\\VS_Code\\cv-maker\\node_modules\\unofficial-chatgpt-api\\build\\ChatGPTClient.js:70:31)\n    at Object.onceWrapper (node:events:646:26)\n    at ClientRequest.emit (node:events:526:28)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:618:27)\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)\n    at TLSSocket.socketOnData (node:_http_client:482:22)\n    at TLSSocket.emit (node:events:526:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)"},"gip":true,"scriptLoader":[]}</script></body></html>`

**Comment by abacaj** [comment]
Won't work anymore they are doing TLS fingerprinting, will need to use a browser: https://github.com/terry3041/pyChatGPT

**Comment by khoatran1602** [comment]
thanks
